package net.hneb.jxetyy.entity;

import lombok.Data;

import javax.persistence.Id;
import javax.persistence.Table;
import java.util.Date;

/**
 * t_lbpc_quest
 */
@Data
@Table(name = "t_lbpc_quest")
public class LbpcQuest implements java.io.Serializable {

	private static final long serialVersionUID = -2217374227080425015L;

	// Fields
	@Id
	private String CPkId;
	private String COrgPkId;
	private String CPkgId;
	private String CSvcPkgId;
	private Integer NSeqNum;
	private String CLbId;
	private String CChildId;
	private String CParentId;
	private String CChildNme;
	private String CChildSex;
	private String TBirthday;
	private String CPhoneNo;
	private Integer NYear;
	private Integer NMonth;
	private Integer NDay;
	private Integer NConceiveWeek;
	private Integer NConceiveDay;
	private String TPreBirth;
	private Integer NYear1;
	private Integer NMonth1;
	private Integer NDay1;
	private Float NBirthHeight;
	private Float NBirthWeight;
	private Float NBirthChest;
	private Float NBirthSheight;
	private Float NBirthHead;
	private String CDptId;
	private String COfficeId;
	private String CDoctor;
	private String CExecutor;
	private String CInfoOffer;
	private String CUserId;
	private Date TTestTm;
	private String CMenzhenNo;
	private String CChildRel;
	private String CIllHistory;
	private String CState;
	private String CEffMrk;
	private String CFormId;

	private String CSchool;
	private String CClazz;
	private String CGrade;

	private Date TCrtTm;
	private String CCrtId;
	private Date TUpdTm;
	private String CUpdId;
	private String CAns1;
	private String CAns2;
	private String CAns3;
	private String CAns4;
	private String CAns5;
	private String CAns6;
	private String CAns7;
	private String CAns8;
	private String CAns9;
	private String CAns10;
	private String CAns11;
	private String CAns12;
	private String CAns13;
	private String CAns14;
	private String CAns15;
	private String CAns16;
	private String CAns17;
	private String CAns18;
	private String CAns19;
	private String CAns20;
	private String CAns21;
	private String CAns22;
	private String CAns23;
	private String CAns24;
	private String CAns25;
	private String CAns26;
	private String CAns27;
	private String CAns28;
	private String CAns29;
	private String CAns30;
	private String CAns31;
	private String CAns32;
	private String CAns33;
	private String CAns34;
	private String CAns35;
	private String CAns36;
	private String CAns37;
	private String CAns38;
	private String CAns39;
	private String CAns40;
	private String CAns41;
	private String CAns42;
	private String CAns43;
	private String CAns44;
	private String CAns45;
	private String CAns46;
	private String CAns47;
	private String CAns48;
	private String CAns49;
	private String CAns50;
	private String CAns51;
	private String CAns52;
	private String CAns53;
	private String CAns54;
	private String CAns55;
	private String CAns56;
	private String CAns57;
	private String CAns58;
	private String CAns59;
	private String CAns60;
	private String CAns61;
	private String CAns62;
	private String CAns63;
	private String CAns64;
	private String CAns65;
	private String CAns66;
	private String CAns67;
	private String CAns68;
	private String CAns69;
	private String CAns70;
	private String CAns71;
	private String CAns72;
	private String CAns73;
	private String CAns74;
	private String CAns75;
	private String CAns76;
	private String CAns77;
	private String CAns78;
	private String CAns79;
	private String CAns80;
	private String CAns81;
	private String CAns82;
	private String CAns83;
	private String CAns84;
	private String CAns85;
	private String CAns86;
	private String CAns87;
	private String CAns88;
	private String CAns89;
	private String CAns90;
	private String CAns91;
	private String CAns92;
	private String CAns93;
	private String CAns94;
	private String CAns95;
	private String CAns96;
	private String CAns97;
	private String CAns98;
	private String CAns99;
	private String CAns100;
	private String CExt1;
	private String CExt2;
	private String CExt3;
	private String CExt4;
	private String CExt5;
	private String CExt6;
	private String CExt7;
	private String CExt8;
	private String CExt9;
	private String CExt10;
	private String CExt11;
	private String CExt12;
	private String CExt13;
	private String CExt14;
	private String CExt15;
	private String CExt16;
	private String CExt17;
	private String CExt18;
	private String CExt19;
	private String CExt20;
	private String CExt21;
	private String CExt22;
	private String CExt23;
	private String CExt24;
	private String CExt25;
	private String CExt26;
	private String CExt27;
	private String CExt28;
	private String CExt29;
	private String CExt30;
}